name: Merge to development
on:
  pull_request:
    types: [ opened, labeled, unlabeled ]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.label.name == 'review' }}
    steps:
      - uses: actions/checkout@master
        with:
          ref: development
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge --no-ff ${{ github.sha }}
          git push