name: Merge to development
on:
  pull_request_review:
    types: [submitted]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@master
        with:
          ref: development
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin pull/${{github.event.pull_request.number}}/head:temp
          git merge --squash --no-edit temp
          git commit -m 'Merged latest from PR ${{github.event.pull_request.number}}';
          git push